# fly.toml app configuration file generated for recipe-be-black-mountain-2497 on 2025-06-21T21:45:59+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recipe-be-black-mountain-2497'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
